# Site settings
title: Developer Portfolio
subtitle: "About a Data Scientist named Bibhash"
url: "https://Bibyutatsu.github.io" # the base hostname & protocol for your site
baseurl: "/Portfolio" # Set this value to "" if you want your site to be root
baseurl: ""
